sudo: false
dist: trusty
language: python

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.6"

install:
  - git fetch --unshallow --tags
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --add channels conda-forge
  - conda update --all -y
  - conda install -y keras numpy pandas pwkit pytoml six

script:
  - pip install --no-deps .
  - neurosynchro --help
